# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          yes | pacman -Syu wget --noconfirm
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          wget https://people.sugarlabs.org/~srevinsaju/dl/appimagetool
          wget https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-556-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          chmod +x appimagetool
          chmod +x appimagetool-556-x86_64.AppImage
          ./appimagetool-556*.AppImage --appimage-extract
          cp appimagetool squashfs-root/usr/bin/appimagetool
          
          rm ./appimagetool-x86_64.AppImage
          ./appimagetool-556*.AppImage squashfs-root
          rm ./appimagetool-556*.AppImage 
          ls
          ./appimagetool*.AppImage squashfs-root
          ls
    
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
